<?php

        header('Content-Type: application/json');
        echo json_encode([
    "success"    => true,
    "errorCode"  => null,
    "errorMsg"   => null,
    "errorTitle" => null,
    "advItems"   => [],
	"result" => [
	    "userId"             => 1,
	    "userIdStr"          => "1",
	    "name"               => "820182",
	    "nickName"           => "820182",
	    "realName"           => "820182",
	    "handle"             => "820182",
	    "email"              => "example@example.com",
	    "password"           => null,
	    "phone"              => null,
	    "icon"               => null,
	    "gender"             => "m",
	    "bid"                => "1",
	    "admin"              => false,
	    "blocked"            => false,
	    "disabled"           => false,
	    "verified"           => false,
	    "verifiedPhone"      => false,
	    "emailVerified"      => true,
	    "reviewer"           => false,
	    "suspicious"         => false,
	    "inCn"               => false,
	    "postNotify"         => false,
	    "registered"         => true,
	    "source"             => 0,
	    "regionCode"         => 0,
	    "regionTitle"        => null,
	    "countryCode"        => null,
	    "scm"                => null,
	    "introduction"       => null,
	    "userDesc"           => "live with passion, live musical.ly",
	    "instagramID"        => null,
	    "googleAccount"      => null,
	    "youtubeChannelId"   => null,
	    "youtubeChannelTitle"=> null,
	    "liveId"             => null,
	    "livelyHearts"       => 0,
	    "recType"            => null,
	    "extProps"           => null,
	    "featuredScope"      => 0,
	    "featuredTime"       => null,
	    "featuredRegions"    => [],
	    "handleModified"     => null,
	    "insertTime"         => null,
	    "updateTime"         => null,
	    "musicalNum"         => 0,
	    "privateMusicalNum"  => 0,
	    "musicalLikedNum"    => 0,
	    "musicalReadNum"     => 0,
	    "likesNum"           => 0,
	    "fansNum"            => 0,
	    "followNum"          => 0,
	    "commentsNum"        => 0,
	    "readNum"            => 0,
	    "followed"           => false,
	    "following"          => false,
	    "complimented"       => false,
	    "followList"         => [],
	    "relationsFromMe"    => [],
	    "relationsToMe"      => [],
	    "sociaMediaList"     => [],
	    "subscribeList"      => [],
	    "userRequestDTO"     => [
	        "follow" => false
	    ],
	    "userSettingDTO"     => [
	        "userId"        => (int)$row["id"],
	        "secret"        => false,
	        "duet"          => false,
	        "hideLocation"  => false,
	        "privateChat"   => false,
	        "directAccount" => null,
	        "policyVersion" => 1,
	        "birthDay"      => null,
	        "birthYear"     => null,
	        "countryCode"   => null,
	        "languageCode"  => null,
	        "timeZone"      => null
	    ]
	],
    "registered" => true,
    "timestamp"  => 1754538451000,
    "fail"       => false
]);
?>
